### PR TITLE
ENYO-3081: Consolidate Strawman logic to initially support common scroller container logic.

### PR DESCRIPTION
**Pull request by aarontam**
### Issue

There are a number of samples that do not include a scroller and, depending on the target device, could result in parts of a sample being unreachable.
### Fix

Rather than add a scroller to every sample, we have attempted to add common scroller logic at a sample-library-level (i.e. assume the samples for a given library either all require a scroller, or none require a scroller), such that this property is at a meta-level and does not have to be set on a given sample, which would muddy the sample code itself. Currently, this feature is enabled for all libraries except `Moonstone`, which uses a different scrolling mechanism. Additionally, we have also consolidated some unnecessary duplication of properties on strawman's `SamplerList` kind for alternate strawman versions (i.e. moonstone-extra). Lastly, removed unnecessary scroller usage for samples whose library has specified the use of a scroller (without removing the scroller, we would end up with nested scrollers that don't actually negatively impact the interactivity of the sample).
### Notes

This might be too large/obtuse of a change to take now, or in general, but wanted to throw this out there as it could be useful for applying certain characteristics or behaviors to our samples en-masse. Additionally, I have decided to replace the removed `Scroller` kinds with `Control` kinds (as opposed to not specifying the kind), as a first step in moving toward `Control.kind` nomenclature; we will need to do this broadly if and when we decide to adopt this approach, and I wanted to hold off on that.

Enyo-DCO-1.1-Signed-off-by: Aaron Tam aaron.tam@lge.com

### CODE REVIEW

**Comment by ryanjduffy** [comment]
~~Rather than adding the `useScroller` property, wdyt about providing a scrolling list that could be extended rather than the existing list?~~

Fixed ... Forgot that the `useScroller` flag isn't really for the list but for the samples the list is loading so my suggestion makes little sense.

**Comment by aarontam** [comment]
Not quite sure what that would look like - do you have something specific in mind? The sample list is effectively replaced when drilling into a specific sample. Also, such frequent (mergeconflict)s!

**Comment by ryanjduffy** [comment]
Figured out what I was thinking before. Check it out here -> 8c8416b

**Comment by aarontam** [comment]
I see! I like it - more Enyo-esque. Didn't realize the list kind was creating the sample as a child component, as opposed to just throwing the sample into the body (wonder if we should consider doing this for the QA version of whatever strawman ends up becoming, to minimize interaction effects). Let me merge your change in and make a tweak. Thanks!

**Pull request merged**
