### PR TITLE
Enyo 2982

### PR DESCRIPTION
**Pull request by webOS101**
Added wip, deprecated and new tags to various samples.

### CODE REVIEW

**Comment by ryanjduffy** [comment]
Do we need to support multiple badges (e.g. WIP and New)? If not, we could collapse the `new`, `wip`, and `deprecated` properties into a `badge` property with string values. Would allow us to avoid using `['new']` to access that prop.

Suggest also that we set the badge in the sample rather than in the respective index.js. It requires more edits but seems like a more appropriate spot to label it.

**Comment by webOS101** [comment]
We don't need to support multiple badges but I'm not sure how you apply a string property to a ::before element.  Maybe Blake knows.  I did think about moving the properties onto the tests themselves.  Not only would it be more work now, but it would be a lot of work later for the 'new' ones when we make them not new.  Seems to make a lot of sense for deprecated and wip, though.

**Comment by ryanjduffy** [comment]
Not suggesting changing the CSS usage -- just mapping the value of `badge` to the CSS class like it does now.

```
// assuming badge name matched the css class, e.g wip
badgeChanged: function (was, is) {
  if (was) this.removeClass(was);
  if (is) this.addClass(is);
}
```

instead of 

```
wipChanged: function () {
  this.addRemoveClass('wip', this.get('wip'));
}
```

"A lot more work" is probably a bit generous. We're talking about removing a line of code from a handful of files. If enyo-strawman were only used by our team, I wouldn't bother with the debate. It is used (and copied!) by others so I think getting the responsibilities right is important even in the small things. Since those are properties of the sample, they should be set in the sample.

**Comment by Djspaceg** [comment]
Here's the version I came up with, based on @ryanjduffy's suggested example:

```
    badgeClassesChanged: function (was, is) {
        if (was) this.addRemoveClasses(was, false);
        if (is) this.addRemoveClasses(is, true);
    },
    addRemoveClasses: function (classes, state) {
        console.log('classes:', classes, state);
        if (classes) {
            classes = classes.split(/\s+/);
            for (var i = 0; i < classes.length; i++) {
                this.addRemoveClass(classes[i], state);
            }
        }
    }
```

This allows for multiple classes (if we need them in the future _(new wip maybe?)_) and does it in a safe way so multiple classes in a different order isn't a dependency of a change. I'll finish this implementation up in the morning. Comments first are welcome.

**Comment by ryanjduffy** [comment]
@Djspaceg Works for me!

**Pull request merged**
