### PR TITLE
Fixes ENYO-1652

### PR DESCRIPTION
**Pull request by ryanjduffy**
Adopt ilib components as submodules

Enyo-DCO-1.1-Signed-off-by: Ryan Duffy (ryan.duffy@lge.com)

### CODE REVIEW

**Comment by gouniLee** [comment]
Hi @ryanjduffy,  I'm trying to do application packaging(i.e. enyo-ilib-samples)  to see the result with your commit https://github.com/enyojs/enyo-ilib/pull/128. I assume you did the pull-request which already works ok. 
But I have a little bit difficulty to work..  Could you see which point did wrongly?
- Checkout  enyo-straman repository with ENYO-1652-ryanjduffy branch.
- Modify enyo-ilib part in enyo-strawman/bower.json as below to get the ilib components as submodules.
  *\*  "enyo-ilib": "git@github.com:enyojs/enyo-ilib.git#ENYO-1547-ryanjduffy"
- Execute egen init 
- Execute epack

but I faced errors as below. (Do I have to modify some path? or some setting were wrong?_
[ 'Error: Cannot find module \'../../../lib/enyo-ilib/lib/Address\' from \'/home/goun/Source/enyo-2.6/enyo-strawman/src/enyo-ilib-samples/lib\'',

Do you have any comments?
Thank you.

**Comment by ryanjduffy** [comment]
You have to use the updated enyo-dev tools with this change because it relies on a feature to specify where the submodules exist (in ilib/lib/ rather than lib/, the default). Run one of the following to get that set up correctly.

If you've `npm install`ed it:

```
npm uninstall -g && git fetch && git checkout unbrowserify && npm prune && npm install && npm install -g
```

Or if you've `npm link`ed it:

```
npm unlink && git fetch && git checkout unbrowserify && npm prune && npm install && npm link
```

**Comment by gouniLee** [comment]
I've tried again as following your comments, but still it doesn't work when I executing 'epack' command. It's not easy for me to figuring out.. Could look through the errors which I got ?
Here's what I did
- enyo-dev is updated with latest and execute your suggested command. 
- checkout your branch in enyo-strawman
- Execute epack

goun@goun:~/Source/enyo-2.6/enyo-strawman$ epack
{"name":"enyo-dev","hostname":"goun","pid":3674,"level":60,"err":{"message":"Object #<Object> has no method 'parse'","name":"TypeError","stack":"TypeError: Object #<Object> has no method 'parse'\n    at module.exports (/home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/lib/parse-path.js:8:16)\n    at loadExternal (/home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/lib/default-resolver.js:236:12)\n    at module.exports (/home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/lib/default-resolver.js:41:9)\n    at ProcessSourceStream._resolve (/home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/index.js:157:2)\n    at ProcessSourceStream._dependency (/home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/index.js:273:47)\n    at /home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/index.js:216:35\n    at Array.forEach (native)\n    at ProcessSourceStream._resolved (/home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/index.js:215:18)\n    at module.exports (/home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/lib/default-resolver.js:55:3)\n    at ProcessSourceStream._resolve (/home/goun/Source/enyo-2.6/enyo-dev/lib/Packager/lib/process-source-stream/index.js:157:2)"},"msg":"Object #<Object> has no method 'parse'","time":"2015-06-23T01:06:34.952Z","v":0}

**Comment by ryanjduffy** [comment]
Appears to be a node version problem. The `parse()` method wasn't added to the path module until v0.11.15. I've been running v.0.12.4 successfully for a while so I'd suggest upgrading to that.

**Comment by ryanjduffy** [comment]
Also, here's the bower.json config you'll need for strawman. I'd expect everything to still build correctly without this but the samples won't work if you don't have the right branches for the other libs.

``` json
{
  "name": "enyo-strawman",
  "dependencies": {
    "enyo": "git@github.com:enyojs/enyo.git#2.6.0-dev",
    "moonstone": "git@github.com:enyojs/moonstone.git#ENYO-1652-ryanjduffy",
    "spotlight": "git@github.com:enyojs/spotlight.git#2.6.0-dev",
    "enyo-ilib": "git@github.com:enyojs/enyo-ilib.git#ENYO-1547-ryanjduffy",
    "layout": "git@github.com:enyojs/layout.git#2.6.0-dev",
    "enyo-cordova": "git@github.com:enyojs/enyo-cordova.git#2.6.0-dev",
    "enyo-webos": "git@github.com:enyojs/enyo-webos.git#2.6.0-dev",
    "onyx": "git@github.com:enyojs/onyx.git#ENYO-1652-ryanjduffy",
    "canvas": "git@github.com:enyojs/canvas.git#2.6.0-dev",
    "svg": "git@github.com:enyojs/svg.git#master"
  },
  "private": true,
  "resolutions": {
    "moonstone-extra": "master"
  }
}
```

**Comment by gouniLee** [comment]
@ryanjduffy , Thank your for your help! After I updated node version on my machine. Executing epack works ok.  :) node version on my machine was v.0.10.*.  After finishing app packaging, I found some error to executing NumberFormatting Sample which is error of iLib. I'll fix it (https://sourceforge.net/p/i18nlib/code/1874/)  then it'll be included next iLb release.

and I have a suggestion. In regards of iLib Sample pages.
There's lots of message in regards of loading resource json datas. such as "
GET file:///home/goun/Source/enyo-2.6/enyo-strawman/dist/resources/strings.json" 
GET file:///home/goun/Source/enyo-2.6/enyo-strawman/dist/resources/en/strings.json 

The reason of this message is missiong ilibmanifest.json in resource/ diretory. In details, ilib try to load resources recursively to the app directory.  Before loading resources, it checks ilibmanifest.json first. ilibmanifest.json  has resource list about its directory. So when I created dist/resource/ilibmanifes.json with contents as below. then it doesn't show error messages.

{"files":[]}

Actually this ilibmanifest.json files is created by localization-tool by webOS build. No need to create manually by developer. but at this local build case, How about creating dummy ilibmanifest.json files as sample in order not to see the useless error message during the app packaging? I want to hear your opinion.

**Comment by graynorton** [comment]
Closed in favor of the rebased equivalent https://github.com/enyojs/enyo-strawman/pull/74

**Pull request closed without merging**
