### PR TITLE
ENYO-3154: enyo-strawman: moonstone-extra incorrect sample paths

### PR DESCRIPTION
**Pull request by JayCanuck**
Enyo-DCO-1.1-Signed-off-by: Jason Robitaille jason.robitaille@lge.com

### CODE REVIEW

**Comment by ryanjduffy** [comment]
So ... how did this even work before? Do we have a bug in enyo-dev that is resolving these into `src` even though they're explicitly relative paths?

**Comment by JayCanuck** [comment]
For me and steven it wasn't working (though we also had other issues we were looking through so maybe unrelated). I suspect not many have tried building moonstone-extra version of strawman in the last few days. Though if it was working for someone, it may purely have been fallback in moduleDir being set to src potentially. The 1.0.0 enyo-dev have a lot of fallbacks that 0.5.3 didn't.

If you're asking how it worked pre-reorganization, the index.js that pulled the samples used to be at the same level as the samples themselves

**Comment by ryanjduffy** [comment]
I just ran `gulp moonstone-extra` without this patch and it built fine. If it is 'falling back', it shouldn't have in this case.

**Comment by ryanjduffy** [comment]
Just verified that enyo-dev will try to find a required module in `moduleDir` if it isn't found in its relative path. I'm considering this a bug and will open a ticket on it.

**Pull request merged**
