### PR TITLE
Enyo-1600 Update sample based on new UX's requirements.

### PR DESCRIPTION
**Pull request by DavidUM**
Enyo-DCO-1.1-Signed-off-by: David Um david.um@lge.com

### CODE REVIEW

**Comment by jefflam22** [comment]
@DavidUM Shouldn't this sample refer to the moonstone-extra repo on these lines?

```
    VideoInfoBackground = require('moonstone/VideoInfoBackground'),
    VideoInfoHeader = require('moonstone/VideoInfoHeader'),
    VideoPlayer = require('moonstone/VideoPlayer');
```

**Comment by DavidUM** [comment]
Thnks @jefflam22

**Comment by Djspaceg** [comment]
This PR will need to be updated to put the new sample in the moonstone-extra directory of strawman instead of the moonstone dir.

**Comment by aarontam** [comment]
Closing in favor of https://github.com/enyojs/enyo-strawman/pull/43.

**Pull request closed without merging**
