### PR TITLE
ENYO-3044: Split strawman into separate apps for each library

### PR DESCRIPTION
**Pull request by JayCanuck**
Enyo-DCO-1.1-Signed-off-by: Jason Robitaille jason.robitaille@lge.com

### CODE REVIEW

**Comment by Djspaceg** [comment]
When I build this branch, it only builds an index file, and none of the libraries load when clicking their buttons. What's the trick to building it successfully?

**Comment by JayCanuck** [comment]
Gotta run:
`gulp`

Various configurations are supported ('gulp moonstone' for moonstone-extra build, 'gulp garnet', and 'gulp sunstone').  In addition, 'gulp build-all' will be all them into a single strawman.

Oh, and -P/--production flag is supported to do production builds of Strawman (devmode builds by default)

If you want to manually build, just run epack on root of project then again for the sampler packages in ./src/*

**Comment by Djspaceg** [comment]
Cool, thanks @JayCanuck! That helps a lot. Can the default `gulp` do the build-all, to make things real easy and straight forward? Is it possible to build moonstone alone, and not moonstone-extra? If so, how do you differentiate the two on the CLI? Having 'moonstone-extra' be referred to as plain 'moonstone' is confusing to me.

**Comment by JayCanuck** [comment]
Ok, I'm renamed it to 'gulp moonstone-extra' for clarity sake.  Current the default gulp task is regular build, which consists of enyo, moonstone, layout, spotlight, enyo-ilib, onyx, canvas, svg, and enyo-webos (note, similar to before enyo-webos button will only actually appear in the launcher on webOS devices). So the default build task includes plain non-extra moonstone.

I'm not eager to make build-all the default, mainly as Strawman is a public-facing utility and build-all attempts to build moonstone-extra, garnet, and sunstone.

**Comment by Djspaceg** [comment]
Awesome. Forget about changing the default to build-all; your existing default sounds perfect already.
Thanks again, @JayCanuck!

**Comment by JayCanuck** [comment]
Closing; recreated based off current master at https://github.com/enyojs/enyo-strawman/pull/262

**Pull request closed without merging**
